# nome da Pipeline
name: Run Basic Testes

# em que momento sera executada
on:
  pull_request:
    branches: [master]



jobs:
# o que vai ser feito nessa Pipeline
# so teremos um job: rodar os testes
  cypress-run:
  # maquina que ira executar o script
    runs-on: ubuntu-latest

# passo a passo para rodar os teste    
    steps:
    # clone do projeto
      - name: Checkout/clone do projeto
        uses: actions/checkout@v3

#exemplo de execução no terminal
      - name: Instalar dependencias do projeto
        run: echo emival Ferreira    

# exemplo de execução no terminal
      - name: Run testes
        uses: cypress-io/github-action@v5
        with:
          record: true
        env:
            CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}